In [1]:
import numpy as np

In [5]:
a = np.array(range(5)) # declare an array of 5 elements from 0

###### attributes of array

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
print(a.dtype) # data type of the array

int32


In [11]:
print(a.size) # size of the array

5


In [12]:
print(a.strides) # number of strides 

(4,)


In [13]:
print(a.ndim) # dimension of the array

1


######  types of arrays (array from random numbers)

In [6]:
 x1 = np.random.randint(10, size = 4) # random numbers from 0 to 10 and
#array size 4
x2 = np.random.randint(10, size = (2,4))
x3 = np.random.randint(10, size = (3,4))

In [15]:
 x1 # 1 dimensional array

array([1, 6, 6, 3])

In [16]:
 x2 # 2 dimensional array 

array([[5, 1, 6, 6],
       [6, 3, 2, 4]])

In [17]:
x3 # 3 dimensional array

array([[8, 2, 0, 9],
       [0, 5, 1, 4],
       [9, 5, 0, 4]])

###### accesing sinlg elements in an array (indexing) 

In [18]:
x1

array([1, 6, 6, 3])

In [19]:
x1[0]

1

In [20]:
x1[-1]

3

In [21]:
x2

array([[5, 1, 6, 6],
       [6, 3, 2, 4]])

In [22]:
x2[0,0] # raw 0 column 0

5

In [23]:
 x2[0,1] #raw 0 column 1

1

In [48]:
x2[1,2] # raw 1 column 2

7

In [50]:
x2[1,-1]

2

In [51]:
x3

array([[3, 9, 9, 1],
       [5, 8, 1, 9],
       [9, 0, 3, 2]])

In [53]:
x3[1,-1]

9

In [54]:
x3[1,1]

8

In [55]:
x3[2,0]

9

###### array scilicing and concatenating 
###### 1. single dimension array 

In [21]:
x1

array([4, 4, 2, 2])

In [22]:
x1[:] # accessing all items in the array

array([4, 4, 2, 2])

In [23]:
x1[0:1] # one item before to the index

array([4])

In [39]:
x1[1:3] # items from index 1 (included) to index 3(not included)

array([6, 6])

In [20]:
x1[::3] #items from index 0(inclussive and jump to item on index 3(inclusive) ) 

array([4, 2])

In [24]:
x1[::-1] ## all items are reversed

array([2, 2, 4, 4])

In [25]:
x1[-1:] # returns the last item in the array

array([2])

In [26]:
x1[-3:] # returns all items to 3 from the last item

array([4, 2, 2])

###### 2. 2 dimension array

In [27]:
x2

array([[9, 0, 2, 0],
       [8, 2, 6, 1]])

In [28]:
x2[0,:1]

array([9])

In [33]:
x2

array([[9, 0, 2, 0],
       [8, 2, 6, 1]])

In [35]:
x2[:1, :3]

array([[9, 0, 2]])

In [19]:
x3

array([[8, 4, 6, 8],
       [7, 4, 3, 7],
       [5, 3, 5, 0]])

In [30]:
x3[:2, :3] ## returns the first two raw each with items from index 0 to 2

array([[8, 4, 6],
       [7, 4, 3]])

In [36]:
x3[:3, ::2] # returns all the three raws each with items from index 0 skipping 1 item


array([[8, 6],
       [7, 3],
       [5, 5]])

In [37]:
x3[::-1, ::-1] ## reverses all rawa and columns 

array([[0, 5, 3, 5],
       [7, 3, 4, 7],
       [8, 6, 4, 8]])

###### accessing raws and columns of multidimenssional arrays

In [41]:
x3

array([[8, 4, 6, 8],
       [7, 4, 3, 7],
       [5, 3, 5, 0]])

In [38]:
x3[:,0] # returns the first column

array([8, 7, 5])

In [39]:
x3[0, :] # returns the first raw

array([8, 4, 6, 8])

###### extracting subarrays

In [40]:
x3

array([[8, 4, 6, 8],
       [7, 4, 3, 7],
       [5, 3, 5, 0]])

In [42]:
x3_sub = x3[:2, :2] # create the sub array
print(x3_sub) # returns first two raws and first 2 columns

[[8 4]
 [7 4]]


In [43]:
x3_sub[0,0]= 26
print(x3_sub) #replaces the item at raw 0 and column 0 of the sub array with 26

[[26  4]
 [ 7  4]]


In [44]:
x3 # the change is also reflected in the original array

array([[26,  4,  6,  8],
       [ 7,  4,  3,  7],
       [ 5,  3,  5,  0]])

In [45]:
x3_sub_copy = x3[:2, :2].copy() # creats a copy of a sub array
print(x3_sub_copy)

[[26  4]
 [ 7  4]]


In [46]:
x3_sub_copy[0, 0] = 53 # changes the item at raw 0 and column 0 to 53
print(x3_sub_copy)

[[53  4]
 [ 7  4]]


In [47]:
x3 # changes to the copy of the sub array do not affect the original array

array([[26,  4,  6,  8],
       [ 7,  4,  3,  7],
       [ 5,  3,  5,  0]])

###### reshaping of arrays
two methods are used 
1. reshape()
2. newaxis()

In [51]:
 y = np.array([2, 5, 7, 8])

In [54]:
y_reshape = y.reshape(4, 1) # using the reshape() method
print(y_reshape)

[[2]
 [5]
 [7]
 [8]]


In [56]:
y_newaxis = y[:, np.newaxis]
print(y_newaxis)

[[2]
 [5]
 [7]
 [8]]


###### concatenating array
cancatenating means joining/merge  two arrays together into a single array
#### note.
 2d and 3d arrays can be concatenated  by raw  or  by column 
 
 #### 1 dimenssional array

In [64]:
array_1d_1 = np.array(range(5))


In [65]:
array_1d_1

array([0, 1, 2, 3, 4])

In [67]:
array_1d_2 = np.array([6, 9, 3, 7])


In [68]:
array_1d_2

array([6, 9, 3, 7])

In [73]:
conc_array = np.concatenate((array_1d_1, array_1d_2)) # concatenating thew array 

In [74]:
conc_array ## returns the concatenated array

array([0, 1, 2, 3, 4, 6, 9, 3, 7])

#### 2 dimenssional array

In [80]:
array_2d_1 = np.arange(6).reshape(2, 3)
array_2d_2 = np.arange(7,12).reshape(2, 3) # creates an array from 7 to 12

In [81]:
array_2d_1

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
array_2d_2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
conc_2d_array_raw = np.concatenate((array_2d_1, array_2d_2)) # cocatenation by raw

In [87]:
conc_2d_array_raw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
conc_2d_array_column = np.concatenate((array_2d_1, array_2d_2), axis = 1)
# concatenation by column

In [92]:
conc_2d_array_column # returns the concatenated array

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

##### vstack() and hstack() functions
these stack/combineh  arrays verticall and horrizontall
these call on the concatenate with axis = 0 and axis =1

##### vstack()

In [102]:
x = np.arange(5, 11).reshape(2, 3)


In [104]:
x

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [105]:
y

array([[12, 13, 14],
       [15, 16, 17]])

In [106]:
np.vstack((x, y))

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [12, 13, 14],
       [15, 16, 17]])

vstack() can be used to combine two 1d arrays to one 2d nummpy array

In [109]:
 r = np.arange(1, 5).reshape(1,4)
s = np. arange(5,9).reshape(1,4)

In [110]:
r

array([[1, 2, 3, 4]])

In [111]:
s

array([[5, 6, 7, 8]])

In [112]:
np.vstack((r, s))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

with transpose(flip raws become columns) we get 2d array of 4X2 using  vstack

In [113]:
np.vstack((r, s)).T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### hstack() 
the result is the same as concatenate with axis = 1

In [114]:
x

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [115]:
y

array([[12, 13, 14],
       [15, 16, 17]])

In [116]:
np.hstack((x,y))

array([[ 5,  6,  7, 12, 13, 14],
       [ 8,  9, 10, 15, 16, 17]])

###### splitting of arrays 

In [153]:
x1 = np.array([1, 3, 4, 5, 6, 7,8]) # declare the array
x2, x3, x4 = np.array_split(x1,3) # spliting the array
print(x2)

[1 3 4]


In [149]:
x2[0] # accessing element of the split

1

In [151]:
x4

array([7, 8])

######  spliting 2d arrays

In [156]:
z = np.array([[6, 7, 9,],
              [10, 11, 13],
              [14, 15, 16]])
w = np.array_split(z, 3)
print(w)

[array([[6, 7, 9]]), array([[10, 11, 13]]), array([[14, 15, 16]])]


In [157]:
v = np.vsplit(z, 3) # vertical split
print(v)

[array([[6, 7, 9]]), array([[10, 11, 13]]), array([[14, 15, 16]])]


In [158]:
h = np.hsplit(z, 3) # horrizontal split
print(h)

[array([[ 6],
       [10],
       [14]]), array([[ 7],
       [11],
       [15]]), array([[ 9],
       [13],
       [16]])]
