###### comparison operators
The Python Numpy comparison operators and functions used to compare the array items and returns Boolean True or false. The Python Numpy comparison functions are greater, greater_equal, less, less_equal, equal, and not_equal. Like any other, Python Numpy comparison operators are <, <=, >, >=, == and != <br>
the result is called aboolean array

In [2]:
import numpy as np

In [29]:
x = np.arange(6,15).reshape(3,3)
y = np.arange(0,6).reshape(2,3)
z = np.arange(15,19)
print(z)


[15 16 17 18]


In [72]:
np.sum(z)

66

In [19]:
np.greater(z,2) # greater than 2

array([ True,  True,  True,  True])

In [20]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.less(y,3.5) # less than

array([[ True,  True,  True],
       [ True, False, False]])

In [71]:
print(y[np.less(y,3.5)]) # returns the elements

[0 1 2 3]


In [74]:
np.sum(y[np.less(y,3.5)])# sum of the elements

6

In [22]:
x

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
np.greater_equal(x,10) # greater equal

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [24]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.less_equal(y,3) # less or equal

array([[ True,  True,  True],
       [ True, False, False]])

In [30]:
x

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
np.equal(x,11)

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [32]:
z

array([15, 16, 17, 18])

In [33]:
np.not_equal(z,17)

array([ True,  True, False,  True])

In [35]:
z < 10

array([False, False, False, False])

In [36]:
z != 17

array([ True,  True, False,  True])

In [37]:
q = np.array([15, 10, 4, 12])

In [38]:
q

array([15, 10,  4, 12])

In [39]:
z != q

array([False,  True,  True,  True])

In [40]:
z == q

array([ True, False, False, False])

In [69]:
print(z[z != q]) # returns numbers of z
# not equal to q

[16 17 18]


###### atttrue & sometrue 
returns true if all elements in the array certisify a certain cretaria 

In [41]:
z

array([15, 16, 17, 18])

In [42]:
np.alltrue(np.greater(z,10))

True

In [43]:
np.alltrue(np.less(z,16))

False

In [44]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
np.sometrue(y < 3) # some elements are 
                   # greater than 3

True

###### counting entries 
we use np.count, np.sum

In [49]:
x

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
np.count_nonzero(x <10)

4

In [51]:
np.sum(x<10)

4

In [52]:
np.sum(x < 10, axis=1) #  counts the number 
# of elements less than 10 in each raw

array([3, 1, 0])

###### np.all and np.any
np.all - returns true if all elements  <br>
np.any - returns true if any of the elements

In [53]:
x

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
np.all(x < 13)

False

In [55]:
np.any(x < 13)

True

In [59]:
np.sum(np.any(x > 13))

1

######  logical operators on boolean  array 


~ - negation (logical “not”) <br>

& -  logical “and”<br>

| - logical “or”

In [60]:
x

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [64]:
c = ~(x%3 == 0) #all elements of x not 
                #divisable by 3
print(c)

[[False  True  True]
 [False  True  True]
 [False  True  True]]


In [66]:
b = (x%3 == 0) & (x%2 == 0) # all elements of
# of X didvisable b 3 and 2
print(b)

[[ True False False]
 [False False False]
 [ True False False]]


In [67]:
a = (x%3 == 0) | (x%2 == 0)
print(a)

[[ True False  True]
 [ True  True False]
 [ True False  True]]


######  array masking
reurns an array of elements that are true to the condition 

In [75]:
print(x[a]) # returns all elements of x that retun true

[ 6  8  9 10 12 14]


In [76]:
np.sum(x[a]) # returns the sum of x that return true

59

In [79]:
x[a] = 3# assigns all ellements true to condition to 3
print(x) 

[[ 3  7  3]
 [ 3  3 11]
 [ 3 13  3]]
