In [1]:
import numpy as np

### Arithmetic on array
Strictly, arithmetic may only be performed on arrays that have the same dimensions and dimensions with the same size.<br>
This means that a one-dimensional array with the length of 10 can only perform arithmetic with another one-dimensional array with the length 10.<br>
###### array Broadcasting 
Broadcasting is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size.
<b>the smaller</b> array is “broadcast” across the larger array so that they have compatible shapes.

In [14]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,10)
b = np.arange(10, 19).reshape(3,3)
c = 2
print("b = ", b)
print("x = ", x)
print("y = ", y)

b =  [[10 11 12]
 [13 14 15]
 [16 17 18]]
x =  [[1 2 3]
 [4 5 6]]
y =  [7 8 9]


In [12]:
print(y + c) #scalar and one dimensional array

[ 9 10 11]


In [11]:
print(x + c)#scalar and 2 dimensional array

[[3 4 5]
 [6 7 8]]


In [15]:
print(b + c)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


In [10]:
 z = x + y#1 dimensional and 2 dimensionl array
print(z)

[[ 8 10 12]
 [11 13 15]]


###### limitations of broadcasting
Arithmetic, including broadcasting, can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1. 