In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5, 6, 8])

#### arithematic operations

Operator	Equivalent ufunc	Description
+	        np.add	            Addition (e.g., 1 + 1 = 2)
-	        np.subtract	        Subtraction (e.g., 3 - 2 = 1)
-	        np.negative	        Unary negation (e.g., -2)
*	        np.multiply	        Multiplication (e.g., 2 * 3 = 6)
/	        np.divide	        Division (e.g., 3 / 2 = 1.5)
//	        np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**       	np.power	        Exponentiation (e.g., 2 ** 3 = 8)
%	        np.mod	            Modulus/remainder (e.g., 9 % 4 = 1)

In [3]:
add = np.add(x, 10)
print(add)

[13 14 15 16 18]


In [5]:
y = np.array([[3, 5, 7],
              [8, 9, 2],
              [4, 10, 11]])
mult = np.multiply(y, 5)
print(mult)

[[15 25 35]
 [40 45 10]
 [20 50 55]]


In [6]:
powers = np.power(y, 2)
print (powers)

[[  9  25  49]
 [ 64  81   4]
 [ 16 100 121]]


######  trigonometric functions (np.function(array))

###### sin, cos, tan	      
compute sine, cosine and tangent of angles
###### arcsin, arccos, arctan	
calculate inverse sine, cosine and tangent
###### hypot	              
calculate hypotenuse of given right triangle
###### sinh, cosh, tanh	  
compute hyperbolic sine, cosine and tangent
###### arcsinh, arccosh, arctanh	 
compute inverse hyperbolic sine, cosine and tangent
###### deg2rad	                 
convert degree into radians
###### rad2deg	                 
convert radians into degree

#### example

In [9]:
angles = np.array([30, 40, 80])
radian = np.deg2rad(angles)
sine = np.sin(radian)
print(sine)

[0.5        0.64278761 0.98480775]


In [11]:
arc = np.sinh(sine)
print(arc)

[0.52109531 0.68797516 1.15189305]


###### statistical function
###### amin, amax	
returns minimum or maximum of an array or along an axis
###### ptp	
returns range of values (maximum-minimum) of an array or along an axis
###### percentile(a, p, axis)	
calculate pth percentile of array or along specified
axis
.Percentiles are used in statistics to give you a number that describes the value that a given percent of the values are lower than
Example: Let's say we have an array of the ages of all the people that lives in a street.

ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

What is the 75. percentile? The answer is 43, meaning that 75% of the people are 43 or younger.
###### median	
compute median of data along specified axis
###### mean	
compute mean of data along specified axis
###### std	
compute standard deviation of data along specified axis
###### var	
compute variance of data along specified axis
###### average	
compute average of data along specified axis


#### example

In [12]:
num = np.array([30, 45, 10, 20, 47, 34])
variance = np.var(num)
print(variance)

170.66666666666666


In [69]:
print(num.max())

47


In [13]:
ranges = np.ptp(num)
print(ranges)

37


In [16]:
perc = np.percentile(num, 70)
print(perc)

39.5


###### logarithms
log2 and log10

In [21]:
x

array([3, 4, 5, 6, 8])

In [23]:
log2 = np.log2(x)
print(log2)

[1.5849625  2.         2.32192809 2.5849625  3.        ]


In [24]:
y

array([[ 3,  5,  7],
       [ 8,  9,  2],
       [ 4, 10, 11]])

In [28]:
log10 = np.log10(y)
print(log10)

[[0.47712125 0.69897    0.84509804]
 [0.90308999 0.95424251 0.30103   ]
 [0.60205999 1.         1.04139269]]


### advanced ufunc

###### specifying the array to store the outcome 

In [39]:
z = np.arange(1, 6)
v = np.empty(5) # empty array to store the out come
np.multiply(z, 8, out=v)
print(v)

[ 8. 16. 24. 32. 40.]


######  specifying how the outcome should be 

In [54]:
w = np.arange(2, 8)
s = np.multiply.outer(w,8)
print(s)
print(s[::2])

[16 24 32 40 48 56]
[16 32 48]


######  using reduce
this reduces the array using the operand and displays the final answer. for example an array x= [2, 5, 6, 7] using np.add.reduce(x) will be (2+5+6+7) giving the result as 20

In [58]:
q = np.arange(4, 9)
p= np.add.reduce(q)
print(q)
print(p)

[4 5 6 7 8]
30


###### using accumulate
this gives the acculative value

In [60]:
q

array([4, 5, 6, 7, 8])

In [59]:
print(np.add.accumulate(q))

[ 4  9 15 22 30]


###### the outer function
this can compute a pair of two different in puts

In [68]:
g = np.arange(2, 6)
h = np.arange(2,6)
gxh = np.multiply.outer(g ,h)
print("g = ", g)
print("h = ", h)
print("g x h = ","\n", gxh)

g =  [2 3 4 5]
h =  [2 3 4 5]
g x h =  
 [[ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]
 [10 15 20 25]]


In [61]:
x = np.arange(1, 5)
y= np.multiply.outer(x, x)

In [62]:
y

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])